name: code_butler_flutter
description: Flutter app for code_butler
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  code_butler_client:
    path: ../code_butler_client
  serverpod_flutter: ^3.0.0
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  flutter_web_auth_2: ^6.0.0
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  fl_chart: ^0.65.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

